-   id: env-sample-sync
    name: env.sample sync
    description: Automatically and safely synchronize .env files with env.sample
    entry: env-sample-sync.sh
    language: script
    always_run: true
    pass_filenames: false
    stages: [commit]
